name: akilli_doktor_asistani
description: Profesyonel hastane yönetim sistemi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^2.1.7
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  mobile_scanner: ^3.5.6
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
